---
layout: Resume
title: Roy Morin's Resume
---
# Roy Morin
Student

<a href="https://www.linkedin.com/in/roy-morin/">My LinkenIn page</a>
</div>


## Currently

Attending BYU Idaho majoring in Statistics

### Specialized in

R Studio, Python.

### Research interests

Mathematics, Statistics.


## Education

`2020-2023`
__Western Wyoming Community College, Wyoming__
__Mathematics Associates Degree__

`2023 - current`
__Brigham Young University Idaho, Idaho__
__Statistics Bachelor's Degree__


## Awards

`2019`
Staff vs Student GRHS Basketball Game MVP


## Occupation

`2011 - 2016`
__Green River Star__, Wyoming

- Pickup and fold newspapers
- Deliver newspapers to individual houses and apartments

`Summers of 2017-2020`
__City of Green River Parks Department__, Wyoming

- Weedeating and edging public parks and walkways.
- Cleaning and maintaining baseball and solftball fields.
- Measuring and painting soccer and football and baseball fields.
- Mowing public parks and grass city owned grass patches around town.




<!-- ### Footer

Last updated: Sept 2024 -->